<?php
/**
 * copied from xclam_currency_converter
 */
$currency['GBP'] = '&pound;';
$currency['EUR'] = '&euro;';
$currency['USD'] = '$';
$currency['CAD'] = '$';
$currency['AUD'] = '$';
$currency['SGD'] = '$';
//$currency['EGP'] = '&pound;';
//$currency['ARS'] = '$';
//$currency['BBD'] = '$';
$currency['BRL'] = 'R$';
//$currency['CLP'] = '$';
$currency['CNY'] = '&#20803;';
$currency['CZK'] = 'K&#269;';
$currency['DKK'] = 'kr';
//$currency['XCD'] = '$';
//$currency['EEK'] = 'kr';
$currency['HKD'] = '&#20803;';
$currency['HUF'] = 'Ft';
//$currency['ISK'] = 'kr';
$currency['INR'] = 'Rs';
$currency['IDR'] = 'Rp';
$currency['ILS'] = '&#8362;';
//$currency['JMD'] = 'J$';
$currency['JPY'] = '&#165;';
$currency['LVL'] = 'Ls';
//$currency['LBP'] = '$pound;';
$currency['LTL'] = 'Lt';
$currency['MYR'] = 'RM';
$currency['MXN'] = '$';
//$currency['NAD'] = '$';
//$currency['NPR'] = 'Rs';
$currency['NZD'] = '$';
$currency['NOK'] = 'kr';
//$currency['OMR'] = '&#65020;';
//$currency['PKR'] = 'Rs';
//$currency['PAB'] = 'B/.';
$currency['PHP'] = 'Ph';
$currency['PLN'] = 'z&#322;';
//$currency['QAR'] = '&#65020;';
$currency['RON'] = 'le';
$currency['RUB'] = 'py6';
//$currency['SAR'] = '&#65020;';
$currency['ZAR'] = 'R';
$currency['KRW'] = '&#8361;';
//$currency['LKR'] = 'Rs';
$currency['SEK'] = 'kr';
$currency['CHF'] = 'CHF';
$currency['THB'] = '&#3647;';
$currency['TRY'] = 'YTL';
//$currency['VEF'] = 'Bs';

/**
 * added number format
 */
$number_format['GBP'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['EUR'] = array( 'dp' => ',', 'ts' => '.' );
$number_format['USD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['CAD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['AUD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['SGD'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['EGP'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['ARS'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['BBD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['BRL'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['CLP'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['CNY'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['CZK'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['DKK'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['XCD'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['EEK'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['HKD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['HUF'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['ISK'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['INR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['IDR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['ILS'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['JMD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['JPY'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['LVL'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['LBP'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['LTL'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['MYR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['MXN'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['NAD'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['NPR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['NZD'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['NOK'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['OMR'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['PKR'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['PAB'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['PHP'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['PLN'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['QAR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['RON'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['RUB'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['SAR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['ZAR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['KRW'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['LKR'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['SEK'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['CHF'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['THB'] = array( 'dp' => '.', 'ts' => ',' );
$number_format['TRY'] = array( 'dp' => '.', 'ts' => ',' );
//$number_format['VEF'] = array( 'dp' => '.', 'ts' => ',' );
